name: Deploy Spring Boot Backend to EC2

on:
  push:
    branches:
      - dev

jobs:
  backend-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Spring Boot app
        run: ./mvnw clean package -DskipTests
        working-directory: backend/inventory

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: backend/inventory/target/*.jar
          target: ~/
          debug: true

      - name: SSH and run Spring Boot app
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            pkill -f 'java -jar' || true
            chmod 755 ~/backend/inventory/target/inventory-0.0.1-SNAPSHOT.jar
            nohup java -jar ~/backend/inventory/target/inventory-0.0.1-SNAPSHOT.jar --server.address=0.0.0.0 > app.log 2>&1 &
